### ISSUE TITLE
Research on SDKs

### ISSUE THREAD

**Issue by hanadi92** [TechForPalestine/offline-chat-app#1]
Research would include evaluation of the following:
- Supported platforms
- Ease of use for developers
- Maintenance frequency

List of SDKs:
- Melon mentioned [nRF](https://github.com/NordicSemiconductor).
- [libp2p rust sdk](https://libp2p.io/)

Android & iOS:
- [Flutter BLE](https://github.com/boskokg/flutter_blue_plus) scanner, read write characteristics
- [Flutter BLE](https://github.com/PhilipsHue/flutter_reactive_ble) scanner, read write characteristics
- [Flutter BLE peripheral](https://github.com/juliansteenbakker/flutter_ble_peripheral)
    - doesn't have a GATT server yet, therefore cannot connect to these devices [PR](https://github.com/juliansteenbakker/flutter_ble_peripheral/pull/155)

Android Only:
- Native android BLE [samples](https://github.com/android/platform-samples/blob/main/samples/connectivity/bluetooth/ble/README.md).
- Native android Wifi-Direct [Docs](https://developer.android.com/develop/connectivity/wifi/wifip2p)
- [Flutter android Wifi-Direct](https://pub.dev/packages/flutter_p2p_connection)

**Comment by smashah** [comment]
https://bridgefy.me/sdk/

This was used by the pro-democracy hong kong protestors
