### ISSUE TITLE
Research on current FOSS Apps

### ISSUE THREAD

**Issue by hanadi92** [TechForPalestine/offline-chat-app#2]
Research would include evaluation of the following:
- Complete open source. (seen some with closed protocol libs e.g. underdark)
- Supported platforms
- Simplicity
- Size of distributable (keep in the back of your head).

List of apps:
- [Qaul](https://github.com/qaul/qaul.net)
- [Briar](https://code.briarproject.org/briar)
   - Stacked App with tons of under-the-hood features:
      - Internet connection & sync possibility + over TOR (both not needed atm)
   - Android Only
- [Android](https://github.com/android/connectivity-samples/tree/main/BluetoothLeChat/app) & [Source](https://github.com/android/platform-samples/tree/main/samples/connectivity/bluetooth/ble)
    - app sample following the native android BLE.

**Comment by hanadi92** [comment]
_This comment will keep updating along the way.._

Briar:
- Stacked App with tons of under-the-hood features:
    - Internet connection & sync possibility + over TOR (both not needed atm)
    - .. 
- Android Only

**Comment by bug-author** [comment]
some open source projects around this idea: https://github.com/topics/bluetooth-chat

**Comment by MrM8BRH** [comment]
- [Mastodon](https://github.com/mastodon/mastodon)
- [Element](https://element.io/)
- [Simplex Chat](https://simplex.chat/) 
- [IronCircles](https://ironcircles.com/)
- [qaul – قول](https://qaul.net/)
- [Bridgefy](https://bridgefy.me/)
- [Jami](https://jami.net/#)
- [Tox](https://tox.chat/)
- [XMPP](https://xmpp.org/)
- [Keybase](https://keybase.io/)
- [RetroShare](https://retroshare.cc/downloads.html)
- [Manyverse](https://www.manyver.se/)
- [Briar Project](https://briarproject.org/)
- [Meshenger](https://cloudflare.f-droid.org/en/packages/d.d.meshenger/)
- [Serval Mesh](https://cloudflare.f-droid.org/en/packages/org.servalproject/)

**Comment by array-in-a-matrix** [comment]
>     * [Element](https://element.io/)

Element is an app (client) built for the [Matrix](https://matrix.org) network similar to how Gajim is a client for XMPP.

**Comment by array-in-a-matrix** [comment]
The Tech For Palestine should have a matrix room bridged to discord as not everyone has/uses discord.
